In [ ]:
import pandas as pd
df= pd.read_csv("titanic.csv")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.shape

(891, 12)

In [ ]:
df.dtypes

In [ ]:
print(df.sort_values(by="Fare", ascending=False))

     PassengerId  Survived  Pclass                                Name  \
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez
258          259         1       1                    Ward, Miss. Anna
737          738         1       1              Lesurer, Mr. Gustave J
88            89         1       1          Fortune, Miss. Mabel Helen
438          439         0       1                   Fortune, Mr. Mark
..           ...       ...     ...                                 ...
806          807         0       1              Andrews, Mr. Thomas Jr
815          816         0       1                    Fry, Mr. Richard
466          467         0       2               Campbell, Mr. William
481          482         0       2    Frost, Mr. Anthony Wood "Archie"
822          823         0       1     Reuchlin, Jonkheer. John George

        Sex        Age  SibSp  Parch    Ticket      Fare Embarked
679    male  36.000000      0      1  PC 17755  512.3292        C
258  female  35.000000      0      0  PC 17755  512.3292        C
737    male  35.000000      0      0  PC 17755  512.3292        C
88   female  23.000000      3      2     19950  263.0000        S
438    male  64.000000      1      4     19950  263.0000        S
..      ...        ...    ...    ...       ...       ...      ...
806    male  39.000000      0      0    112050    0.0000        S
815    male  29.699118      0      0    112058    0.0000        S
466    male  29.699118      0      0    239853    0.0000        S
481    male  29.699118      0      0    239854    0.0000        S
822    male  38.000000      0      0     19972    0.0000        S

[891 rows x 11 columns]

In [ ]:
print(df.sort_values(by="Age", ascending=False))

     PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson
851          852         0       3                   Svensson, Mr. Johan
96            97         0       1             Goldschmidt, Mr. George B
493          494         0       1               Artagaveytia, Mr. Ramon
116          117         0       3                  Connors, Mr. Patrick
..           ...       ...     ...                                   ...
831          832         1       2       Richards, Master. George Sibley
644          645         1       3                Baclini, Miss. Eugenie
469          470         1       3         Baclini, Miss. Helene Barbara
755          756         1       2             Hamalainen, Master. Viljo
803          804         1       3       Thomas, Master. Assad Alexander

        Sex    Age  SibSp  Parch    Ticket     Fare Embarked
630    male  80.00      0      0     27042  30.0000        S
851    male  74.00      0      0    347060   7.7750        S
96     male  71.00      0      0  PC 17754  34.6542        C
493    male  71.00      0      0  PC 17609  49.5042        C
116    male  70.50      0      0    370369   7.7500        Q
..      ...    ...    ...    ...       ...      ...      ...
831    male   0.83      1      1     29106  18.7500        S
644  female   0.75      2      1      2666  19.2583        C
469  female   0.75      2      1      2666  19.2583        C
755    male   0.67      1      1    250649  14.5000        S
803    male   0.42      0      1      2625   8.5167        C

[891 rows x 11 columns]

In [ ]:
print(df[df["Sex"] == "female"])

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
880          881         1       2
882          883         0       3
885          886         0       3
887          888         1       1
888          889         0       3

                                                  Name     Sex        Age  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000
2                               Heikkinen, Miss. Laina  female  26.000000
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000
..                                                 ...     ...        ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.000000
882                       Dahlberg, Miss. Gerda Ulrika  female  22.000000
885               Rice, Mrs. William (Margaret Norton)  female  39.000000
887                       Graham, Miss. Margaret Edith  female  19.000000
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118

     SibSp  Parch            Ticket     Fare Embarked
1        1      0          PC 17599  71.2833        C
2        0      0  STON/O2. 3101282   7.9250        S
3        1      0            113803  53.1000        S
8        0      2            347742  11.1333        S
9        1      0            237736  30.0708        C
..     ...    ...               ...      ...      ...
880      0      1            230433  26.0000        S
882      0      0              7552  10.5167        S
885      0      5            382652  29.1250        Q
887      0      0            112053  30.0000        S
888      1      2        W./C. 6607  23.4500        S

[314 rows x 11 columns]

In [ ]:
print(df[df["Survived"] == 1])

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
875          876         1       3
879          880         1       1
880          881         1       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Embarked
1        0          PC 17599  71.2833        C
2        0  STON/O2. 3101282   7.9250        S
3        0            113803  53.1000        S
8        2            347742  11.1333        S
9        0            237736  30.0708        C
..     ...               ...      ...      ...
875      0              2667   7.2250        C
879      1             11767  83.1583        C
880      1            230433  26.0000        S
887      0            112053  30.0000        S
889      0            111369  30.0000        C

[342 rows x 11 columns]

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [ ]:
df["Age"].mean()

np.float64(29.69911764705882)

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [ ]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [ ]:
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df = df.drop("Cabin", axis=1)

KeyError: "['Cabin'] not found in axis"

In [ ]:
print(df["Age"] > 40)

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
print(df[df["Age"] > 40])

     PassengerId  Survived  Pclass  \
6              7         0       1
11            12         1       1
15            16         1       2
33            34         0       2
35            36         0       1
..           ...       ...     ...
862          863         1       1
865          866         1       2
871          872         1       1
873          874         0       3
879          880         1       1

                                                  Name     Sex   Age  SibSp  \
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
33                               Wheadon, Mr. Edward H    male  66.0      0
35                      Holverson, Mr. Alexander Oskar    male  42.0      1
..                                                 ...     ...   ...    ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0      0
865                           Bystrom, Mrs. (Karolina)  female  42.0      0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
873                        Vander Cruyssen, Mr. Victor    male  47.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0

     Parch      Ticket     Fare Embarked
6        0       17463  51.8625        S
11       0      113783  26.5500        S
15       0      248706  16.0000        S
33       0  C.A. 24579  10.5000        S
35       0      113789  52.0000        S
..     ...         ...      ...      ...
862      0       17466  25.9292        S
865      0      236852  13.0000        S
871      1       11751  52.5542        S
873      0      345765   9.0000        S
879      1       11767  83.1583        C

[150 rows x 11 columns]

In [ ]:
df["Embarked"].mode()[0]

'S'